# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/support/proto/ping.proto

require 'google/protobuf'

descriptor_data = "\n\x1dtest/support/proto/ping.proto\x12\x07support\"0\n\x0bPingRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\r\"\x1d\n\x0cPingResponse\x12\r\n\x05value\x18\x01 \x01(\t2\xa7\x02\n\nPingServer\x12\x44\n\x13RequestResponsePing\x12\x14.support.PingRequest\x1a\x15.support.PingResponse\"\x00\x12\x45\n\x12\x43lientStreamerPing\x12\x14.support.PingRequest\x1a\x15.support.PingResponse\"\x00(\x01\x12\x45\n\x12ServerStreamerPing\x12\x14.support.PingRequest\x1a\x15.support.PingResponse\"\x00\x30\x01\x12\x45\n\x10\x42idiStreamerPing\x12\x14.support.PingRequest\x1a\x15.support.PingResponse\"\x00(\x01\x30\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Support
  PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('support.PingRequest').msgclass
  PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('support.PingResponse').msgclass
end
